#!/bin/sh

now="$(date +%s)"
defer_seconds=${1:-0}

case "${TASK_STATE}" in
  "fail") [ $((TASK_LAST_OK+defer_seconds))   -lt "${now}" ] && exit 0 ;;
  "ok")   [ $((TASK_LAST_FAIL+defer_seconds)) -lt "${now}" ] && exit 0 ;;
esac

exit 1
