#!/bin/sh

NOW="$(date +%s)"
DEFER_SECONDS=${1:-0}

case "${STATE}" in
  "fail") [ $((LAST_OK+DEFER_SECONDS))   -lt "${NOW}" ] && exit 0 ;;
  "ok")   [ $((LAST_FAIL+DEFER_SECONDS)) -lt "${NOW}" ] && exit 0 ;;
esac

exit 1
