#!/bin/sh
steps=$1
threshold=$2
state_changes=0

# shellcheck disable=SC2034
for n in $(seq 1 "${steps}"); do
  # ran out of measurements
  if [ $((HISTORY_MASK & 3)) -ne 3 ]; then
    break
  fi

  last_checks=$((HISTORY & 3))

  # increment counter if it was a state change
  if [ "${last_checks}" -ne 0 ] && [ "${last_checks}" -ne 3 ]; then
    state_changes=$((state_changes+1))
  fi

  # shift the data before continuing
  HISTORY=$((HISTORY>>1))
  HISTORY_MASK=$((HISTORY_MASK>>1))
done

[ "${state_changes}" -lt "${threshold}" ]
