#!/bin/sh

NOW="$(date +%s)"
DELAY_SECONDS=${1:-0}

# exit 1 until the regular notification has been made
case "${LAST_STATE}" in
  "fail") [ "${LAST_NOTIFICATION}" -lt "${LAST_OK}" ] && exit 1 ;;
  "ok")   [ "${LAST_NOTIFICATION}" -lt "${LAST_FAIL}" ] && exit 1 ;;
esac

if [ "${LAST_NOTIFICATION}" -le "$((NOW-DELAY_SECONDS))" ]; then
  exit 0
else
  exit 1
fi
