#!/bin/sh

now="$(date +%s)"
delay_seconds=${1:-0}

# exit 1 until the regular notification has been made
case "${TASK_LAST_STATE}" in
  "fail") [ "${TASK_LAST_NOTIFICATION}" -lt "${TASK_LAST_OK}" ] && exit 1 ;;
  "ok")   [ "${TASK_LAST_NOTIFICATION}" -lt "${TASK_LAST_FAIL}" ] && exit 1 ;;
esac

if [ "${TASK_LAST_NOTIFICATION}" -le "$((now-delay_seconds))" ]; then
  exit 0
else
  exit 1
fi
