#!/bin/sh

case $1 in
  "ok")
    [ "${STATE}" = "ok" ]                           \
      && [ "${LAST_NOTIFICATION}" -le "${LAST_FAIL}" ] \
      && exit 0
    ;;
  "fail")
    [ "${STATE}" = "fail" ]                           \
      && [ "${LAST_NOTIFICATION}" -le "${LAST_OK}" ] \
      && exit 0
    ;;
esac

exit 1
