#!/bin/sh
set -eu
. $(dirname "$0")/../helpers.inc

fz_check_env TASK_STATE
fz_check_env TASK_LAST_NOTIFICATION
fz_check_env TASK_LAST_FAIL
fz_check_env TASK_LAST_OK

case $1 in
  "ok")
    [ "${TASK_STATE}" = "ok" ]                                   \
      && [ "${TASK_LAST_NOTIFICATION}" -le "${TASK_LAST_FAIL}" ] \
      && exit 0
    ;;
  "fail")
    [ "${TASK_STATE}" = "fail" ]                               \
      && [ "${TASK_LAST_NOTIFICATION}" -le "${TASK_LAST_OK}" ] \
      && exit 0
    ;;
  *)
    echo "received invalid argument" >&2
    ;;
esac

exit 1
