#!/bin/sh
set -e

[ -n "${TASK_STATE}" ] \
  || ( echo "TASK_STATE is undefined" >&2 && exit 1 )

[ -n "${TASK_LAST_NOTIFICATION}" ] \
  || ( echo "TASK_LAST_NOTIFICATION is undefined" >&2 && exit 1 )

[ -n "${TASK_LAST_FAIL}" ] \
  || ( echo "TASK_LAST_FAIL is undefined" >&2 && exit 1 )

[ -n "${TASK_LAST_FAIL}" ] \
  || ( echo "TASK_LAST_OK is undefined" >&2 && exit 1 )

set -eu

case $1 in
  "ok")
    [ "${TASK_STATE}" = "ok" ]                              \
      && [ "${TASK_LAST_NOTIFICATION}" -le "${TASK_LAST_FAIL}" ] \
      && exit 0
    ;;
  "fail")
    [ "${TASK_STATE}" = "fail" ]                          \
      && [ "${TASK_LAST_NOTIFICATION}" -le "${TASK_LAST_OK}" ] \
      && exit 0
    ;;
  *)
    echo "received invalid argument" >&2
    ;;
esac

exit 1
