#!/bin/sh
set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env TASK_STATE
fz_check_env TASK_LAST_NOTIFICATION
fz_check_env TASK_LAST_FAIL
fz_check_env TASK_LAST_OK
fz_check_env TASK_LAST_STATE


hasTransition()  { [ "${TASK_STATE}" != "${TASK_LAST_STATE}" ]; }
fromStable()     { [ "${TASK_LAST_STATE}" != "unknown" ]; }
firstDetection() { [ "${TASK_LAST_NOTIFICATION}" -le "${TASK_LAST_FAIL}" ]; }

[ $# -ne 1 ] \
  && ( echo "command did not receive one argument" >&2 && exit 255 )

if [ "$1" != "ok" ] && [ "$1" != "fail" ]; then
    echo "received invalid argument" >&2
    exit 255
fi

hasTransition || exit 1
fromStable || exit 1

if [ "${TASK_STATE}" = "$1" ] && firstDetection; then
  exit 0
else
  exit 1
fi
