log_level = "trace"

[defaults]
retries = 5
timeout = 1
notifiers = [
    "echo"
]
priority = 3

[[task]]
name = "whoami"
command = "whoami"
args = ["--help"]
frequency = 1

[[task]]
name = "ping.localhost"
command = "ping"
args = [ "-A", "-c3", "127.0.0.1" ]
frequency = 3

[[task]]
name = "sleep"
command = "sleep"
args = [ "4" ]
frequency = 1

[[task]]
name = "false"
command = "false"
args = []
frequency = 1

[[notifier]]
name = "echo"
command = "contrib/notifier/echo"
args = []
