log_file = "-"
log_level = "debug"
directory = "/home/jon/src/flamingzombies/libexec"

listen_address = "127.0.0.1:5891"

[defaults]
retries = 5
timeout = 1
notifiers = [
    "logger"
]
priority = 3

#[[task]]
#name = "localhost:ssh"
#command = "/usr/lib/nagios/libexec/check_ssh"
#args = [ "-t", "5", "-r", "9.7", "1.2.3.4"]
#timeout = 6

[[task]]
name = "flappy"
command = "task/flappy"
frequency = 1
error_body = """
flappy has entered an error state
"""
recover_body = """
flappy has recovered
"""

#[[task]]
#name = "whoami"
#command = "/usr/bin/whoami"
#args = ["--help"]
#frequency = 1
#retry_frequency = 1

#[[task]]
#name = "ping.localhost"
#command = "ping"
#args = [ "-A", "-c3", "127.0.0.1" ]
#frequency = 3
#
#[[task]]
#name = "sleep"
#command = "sleep"
#args = [ "4" ]
#frequency = 1
#timeout = 1
#
#[[task]]
#name = "false"
#command = "false"
#args = []
#frequency = 1

[[notifier]]
name = "logger"
command = "notifier/null"
timeout = 5
gates = ["state_change"]

[[gate]]
name = "state_change"
command = "gate/state_change"
timeout = 1
