log_file = "-"
log_level = "info"

[defaults]
retries = 5
timeout = 1
notifiers = [
    "logger",
]
error_notifiers = [
    "error_emailer",
]
priority = 3
envs = [
    ["SNMP_COMMUNITY", "default"],
    ["SNMP_VERSION", "2c"],
]

[[task]]
name = "flappy"
command = "task/flappy"
frequency = 1
error_body = """
flappy has entered an error state
"""
recover_body = """
flappy has recovered
"""

[[notifier]]
name = "logger"
command = "notifier/null"
timeout = 5
gates = [
    ["to_failed", "defer"],
    ["is_failed", "renotify"],
]

[[notifier]]
name = "error_emailer"
command = "notifier/email"
envs = [
    [ "EMAIL_ADDRESS", "jon@altos.au" ],
    [ "EMAIL_FROM", "fz@altos.au" ],
    [ "EMAIL_SUBJECT", "fz experienced a critical error" ],
]
timeout = 3
gates = []

[[gate]]
name = "to_failed"
command = "gate/to_state"
args = ["fail"]

[[gate]]
name = "is_failed"
command = "gate/is_state"
args = ["fail"]

[[gate]]
name = "is_ok"
command = "gate/is_state"
args = ["ok"]

[[gate]]
name = "defer"
command = "gate/defer"
args = ["6"]

[[gate]]
name = "renotify"
command = "gate/renotify"
args = ["5"]
