#!/bin/sh
[ -n "${MAIL_TO}" ] \
  || ( echo "MAIL_TO is undefined" >&2 && exit 1 )

[ -n "${MAIL_FROM}" ] \
  || ( echo "MAIL_FROM is undefined" >&2 && exit 1 )

set -eu

# allow the subject line to be overridden
MAIL_SUBJECT=${MAIL_SUBJECT:-${SUBJECT}}

timeout 0.2 cat <<EOF | mail -r "${MAIL_FROM}" -s "${MAIL_SUBJECT}" "${MAIL_TO}"
${MSG}
---
EOF
