#!/bin/sh
set -e

[ -n "${MAIL_TO}" ] \
  || ( echo "MAIL_TO is undefined" >&2 && exit 1 )

[ -n "${MAIL_FROM}" ] \
  || ( echo "MAIL_FROM is undefined" >&2 && exit 1 )

[ -n "${TASK_TRACE_ID}" ] \
  || ( echo "TASK_TRACE_ID is undefined" >&2 && exit 1 )

[ -n "${MSG}" ] \
  || ( echo "MSG is undefined" >&2 && exit 1 )

set -eu

# allow the subject line to be overridden
MAIL_SUBJECT=${MAIL_SUBJECT:-${SUBJECT}}

timeout 0.2 cat <<EOF | mail -r "${MAIL_FROM}" -s "${MAIL_SUBJECT}" "${MAIL_TO}"
description:
${TASK_DESCRIPTION}

message:
${MSG}
---
${TASK_TRACE_ID}
EOF
