#!/bin/sh
#
# Deliver messages with ntfy.
# https://github.com/binwiederhier/ntfy
#

_send() {
  subject="${NAME}: state ${STATE}"

  case "${PRIORITY}" in
    1) ntfy_priority="max"     ;;
    2) ntfy_priority="high"    ;;
    3) ntfy_priority="default" ;;
    4) ntfy_priority="low"     ;;
    5) ntfy_priority="min"     ;;
    *) ntfy_priority="default" ;;
  esac

  status_tag="gray_question"
  [ "${STATE}" = "ok" ] && status_tag="green_circle"
  [ "${STATE}" = "fail" ] && status_tag="red_circle"

  curl -v -f --data-binary @"${DATAFILE}"                        \
    -H "Title: ${subject}"                                       \
    -H "Priority: ${ntfy_priority}"                              \
    -H "X-Tags: ${status_tag},host:$(hostname -s),${OPEN_GATES}" \
    -H "Markdown: yes"                                           \
    "ntfy.sh/${NTFY_TOPIC}"
}

if [ $# -eq 0 ]; then
  echo "you must supply the topic as first argument" >&2
  exit 1
fi

NTFY_TOPIC="$1"
DATAFILE=$(mktemp)

cat <<EOF > "${DATAFILE}"
> ${RESULT_OUTPUT}
---
$(timeout 0.2 cat)
EOF

_send

rm -f "${DATAFILE}"
