#!/bin/sh
#
# In the example:
#
#   disk_free / 90
#
# the script will return 1 if more than 90% of the disk space is used on the
# file system mounted at /.

df -P \
  | awk -v mount="$1" -v threshold_percent="$2" '
    ($6==mount) { if (int($5) > threshold_percent) { exit 1 }}
  '
