#!/bin/sh

_file_epoch() {
  if [ "$(uname)" = "OpenBSD" ]; then
    stat -f "%m" "$1"
  else
    stat -c %Y "$1"
  fi
}

FILE=$1
MAX_AGE=$2

if [ $# -ne 2 ]; then
    echo "not enough arguments were provided" >&2
    exit 3
fi

NOW=$(date +%s)

if ! [ -f "$1" ]; then
    echo "file '$1' does not exist"
    exit 1
fi

if [ "$(_file_epoch "${FILE}")" -lt "$((NOW-MAX_AGE))" ]; then
  echo "file '${FILE}' is older than ${MAX_AGE} seconds"
  exit 1
fi

exit 0
