#!/bin/sh
set -e

if [ $# -eq 2 ]; then
  export FZ_LISTEN="$1:$2"
fi

if [ "${TIMEOUT}" -le 2 ]; then
  echo "the timeout must be greater than 2 seconds." >&2
  exit 3
fi

tasks="$(timeout 1 fzctl list | awk '{ print $1 }')"
if [ "$(echo "${tasks}" | wc -w)" -eq 0 ]; then
  echo "no tasks were found"
  exit 3
fi

# shellcheck disable=SC2086
timeout 1 fzctl show ${tasks} | awk '
    BEGIN { errors=0 }
    /^name:/ { name=$2 }
    /^errors:/ {
      if ($2>0) {
        print name, "has experienced errors"
        errors++
      }
    }
    END {
      if (errors>0)
        exit 1
    }
  '
