#!/bin/sh
#
# Check a url for a pattern in the response headers.
#
# Usage: http_resp_headers <URL> <PATTERN>...
#

set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env TASK_TIMEOUT

[ $# -lt 2 ] \
  && ( echo "usage: $0 <URL> <HEADER_PATTERN> [HEADER_PATTERN]..." >&2 && exit 255 )

url=$1
shift

TMPFILE="$(mktemp)"
trap 'rm -f "${TMPFILE}"' EXIT INT HUP

curl -m "${TASK_TIMEOUT}" -s -o /dev/null -v "${url}" 2>&1 \
  | grep "^< " \
  | sed 's/^< //' \
  > "${TMPFILE}"

found=true
for pattern in "$@"; do
  if ! grep -E -q "${pattern}" "${TMPFILE}"; then
    echo "${url}: headers do not contain pattern '${pattern}'"
    found=false
  fi
done

if ${found}; then
  echo "${url}: headers contains all expected patterns"
  exit 0
else
  exit 1
fi
