#!/bin/sh
if [ $# -ne 2 ]; then
  echo "usage: $0 <url> <pattern>" >&2
  exit 1
fi

URL=$1
PATTERN=$2
DEADLINE="$(echo "${TIMEOUT:-5}" | awk '{ print $1 - 0.1 }')"

curl -m "${DEADLINE}" -s "${URL}" | grep -E -q "${PATTERN}"
