#!/bin/sh
#
# Check a url for a pattern in the response body.
#
# Usage: http_resp_body <URL> <PATTERN>
#

set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env TASK_TIMEOUT

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 255 )

url=$1
pattern=$2

if curl -m "${TASK_TIMEOUT}" -s "${url}" | grep -E -q "${pattern}"; then
  echo "${url}: contains pattern ${pattern}"
  exit 0
else
  echo "${url}: does not contain pattern ${pattern}"
fi
