#!/bin/sh
#
# checks that the 1m load average is below the threshold.
#

threshold=${1:-1}

loadavg() { uptime | awk '{ sub(",","",$(NF-1)); print $(NF-1) }'; }

la=$(loadavg)

# publish the value as a statsd metric
echo "${STATSD_PREFIX}.loadavg:${la}|g|${STATSD_TAGS}" \
  | nc -w0 -u "$(echo "${STATSD_HOST}" | cut -d: -f1)" "$(echo "${STATSD_HOST}" | cut -d: -f2)"

echo "${la}" \
  | awk -v threshold="${threshold}" '
      {
        if ($1>threshold) {
          print "loadavg (" $1 ") exceeded threshold (" threshold ")"
          exit 1
        } else {
          print "loadavg (" $1 ") is ok"
        }
      }
    '
