#!/bin/sh
#
# checks that the 1m load average is below the threshold.
#

. "$(dirname "$0")/../helpers.inc"

threshold=${1:-1}

loadavg() { uptime | awk '{ sub(",","",$(NF-1)); print $(NF-1) }'; }

la=$(loadavg)

metric_gauge loadavg la

echo "${la}" \
  | awk -v threshold="${threshold}" '
      {
        if ($1>threshold) {
          print "loadavg (" $1 ") exceeded threshold (" threshold ")"
          exit 1
        } else {
          print "loadavg (" $1 ") is ok"
        }
      }
    '
