#!/bin/sh
#
# checks that the 1m load average is below the threshold.
#

threshold=${1:-1}

uptime \
  | awk -v threshold="${threshold}" '
      {
        sub(",","",$(NF-1))
        v=$(NF-1)
      }
      END {
        if (v>threshold) {
          print "loadavg (" v ") exceeded threshold (" threshold ")"
          exit 1
        } else {
          print "loadavg (" v ") is ok"
        }
      }
    '
