#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "first argument must be a mount point" >&2
  exit 1
fi

mount | awk -v mount="$1" '
    BEGIN       { code=1    }
    ($3==mount) { code=0    }
    END         { exit code }
  '

