#!/bin/sh
#
# Check the state of a network interface
#
# Usage: snmp_ifOperStatus <PORT> <SPEED>
#
# Values:
#   up        1
#   down      2
#   testing   3
#
# You can get a list of available ports with:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> ifOperStatus
#

set -e
[ -n "${SNMP_HOST}" ] \
  || ( echo "SNMP_HOST is undefined" >&2 && exit 1 )

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 1 )

set -u

SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

if [ "$(uname -s)" = "OpenBSD" ]; then
  SNMP_GET="snmp get"
else
  SNMP_GET="snmpget -Oe"
fi

ifOperStatus() {
  ${SNMP_GET}              \
    -v "${SNMP_VERSION}"   \
    -c "${SNMP_COMMUNITY}" \
    "${SNMP_HOST}"         \
    "ifOperStatus.$1"      \
    | awk '{ print int($NF) }'
}

statusToString() {
  case "$1" in
    1) echo up ;;
    2) echo down ;;
    3) echo testing ;;
    *) echo "unrecognised value" >&2 && exit 255
  esac
}

status=$(ifOperStatus "$1")
echo "interface $1: $(statusToString "${status}")"
[ "${status}" -eq "$2" ]
