#!/bin/sh
set -e
[ -e "${SNMP_HOST}" ] \
  || ( echo "SNMP_HOST is undefined" >&2 && exit 1 )

[ $# -ne 2 ] \
  || ( echo "command did not receive two arguments" >&2 && exit 1 )

set -u

VOL=$1
THRESHOLD=$2


SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

storageInt() {
  snmp walk -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" hrStorageDescr \
    | awk -v vol="$1" '($NF==vol) { sub("hrStorageDescr\.","",$1); print $1 }'
}

storageAllocationUnits() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageAllocationUnits.${VOL}" \
    | awk '{ print $NF }'
}

storageSize() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageSize.${VOL}" \
    | awk -v n="$2" '{ print $NF * n }'
}

storageUsed() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageUsed.${VOL}" \
    | awk -v n="$2" '{ print $NF * n }'
}

i=$(storageInt "${VOL}")
n=$(storageAllocationUnits "$i")

storageSize "$i" "$n"
storageUsed "$i" "$n"
echo "threshold: ${THRESHOLD}"
