#!/bin/sh
if [ $# -lt 3 ]; then
  echo "usage: $0 <host> <path> <community> <version>" >&2
  exit 1
fi

host=$1
path=$2
community=${3:-public}
version=${4:-2c}

storageInt() {
  snmp walk -v ${version} -c ${community} ${host} hrStorageDescr \
    | awk '($NF=="/") { sub("hrStorageDescr\.","",$1); print $1 }'
}

storageAllocationUnits() {
  snmp get -v ${version} -c ${community} ${host} hrStorageAllocationUnits.$1 \
    | awk '{ print $NF }'
}

storageSize() {
  snmp get -v ${version} -c ${community} ${host} hrStorageSize.$1 \
    | awk -v n=$n '{ print $NF * n }'
}

storageUsed() {
  snmp get -v ${version} -c ${community} ${host} hrStorageUsed.$1 \
    | awk -v n=$n '{ print $NF * n }'
}

i=$(storageInt ${path})
n=$(storageAllocationUnits $i)

storageSize $i $n
storageUsed $i $n
