#!/bin/sh
#
# Ensures that there are at least <MINIMUM> processes named <PROC>.
#
# Usage: snmp_hrSWRun <PROC> <MINIMUM>
#
# You can get a list of available volumes with the command:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> hrSWRunName
#

set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env SNMP_HOST

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 255 )

processCount() {
  ${SNMP_WALK} -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" hrSWRunName \
    | grep -c "STRING: $1$"
}

n=$(processCount "$1")
echo "$1: matches $n processes"

[ "$n" -ge "$2" ]
