#!/bin/sh

if [ $# -lt 3 ]; then
  echo "usage: $0 <host> <interface> <community> <version>" >&2
  exit 1
fi

host=$1
interface=$2
community=${3:-public}
version=${4:-2c}

# returns:
#   1 up
#   2 down
#   3 testing

snmp get -v ${version} -c ${community} ${host} ifOperStatus.$2 \
  | awk '{ print $NF }'
