#!/bin/sh
#
# Check for free space in a volume, swap or memory.
#
# Usage: snmp_hrStorage <VOL> <THRESHOLD_BYTES>
#
# You can get a list of available volumes with the command:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> hrStorageDescr
#

set -e
[ -n "${SNMP_HOST}" ] \
  || ( echo "SNMP_HOST is undefined" >&2 && exit 1 )

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 1 )

set -u

VOL=$1
THRESHOLD=$2

SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

storageInt() {
  snmp walk -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" hrStorageDescr \
    | awk -F= -v vol="$1" '($2~vol) { sub("hrStorageDescr\.","",$1); print int($1) }'
}

storageAllocationUnits() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageAllocationUnits.$1" \
    | awk '{ print $NF }'
}

storageSize() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageSize.$1" \
    | awk -v n="$2" '{ print $NF * n }'
}

storageUsed() {
  snmp get -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" "hrStorageUsed.$1" \
    | awk -v n="$2" '{ print $NF * n }'
}

i=$(storageInt "${VOL}")
n=$(storageAllocationUnits "$i")

storageSize "$i" "$n"
storageUsed "$i" "$n"
echo "threshold: ${THRESHOLD}"
