#!/bin/sh
#
# Check the speed of a network interface
#
# Usage: snmp_ifSpeed <PORT> <SPEED>
#
# Speeds:
#   10Mb       10000000
#   100Mb     100000000
#   1Gb      1000000000
#
# You can get a list of available ports with:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> ifSpeed
#

set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env SNMP_HOST

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 1 )

set -u

SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

if [ "$(uname -s)" = "OpenBSD" ]; then
  SNMP_GET="snmp get"
else
  SNMP_GET="snmpget"
fi

ifSpeed() {
  ${SNMP_GET}              \
    -v "${SNMP_VERSION}"   \
    -c "${SNMP_COMMUNITY}" \
    "${SNMP_HOST}"         \
    "ifSpeed.$1"           \
    | awk '{ print int($NF) }'
}

speed=$(ifSpeed "$1")
echo "interface $1: $(fz_bps_to_string "${speed}")"
[ "${speed}" -eq "$2" ]
