#!/bin/sh
#
# Checks an OpenBSD temperature sensor
#
# Usage: snmp_openbsdSensorTemp <DEVICE> <MAXIMUM>
#
# You can get a list of available devices with the command:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> .1.3.6.1.4.1.30155.2.1.2.1.4
#
# Make sure that the unit of the device is degC using the command:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> .1.3.6.1.4.1.30155.2.1.2.1.6
#

set -eu
. "$(dirname "$0")/../helpers.inc"

fz_check_env SNMP_HOST

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 1 )

id=$1
threshold=$2

temp() {
  ${SNMP_GET} -c "${SNMP_COMMUNITY}" -v "${SNMP_VERSION}" "${SNMP_HOST}" ".1.3.6.1.4.1.30155.2.1.2.1.5.$1" \
    | awk '{ gsub("\"","",$NF); print $NF }'
}

device_name() {
  ${SNMP_GET} -c "${SNMP_COMMUNITY}" -v2c "${SNMP_HOST}" ".1.3.6.1.4.1.30155.2.1.2.1.4.$1" \
    | awk '{ gsub("\"","",$NF); print $NF }'
}

t=$(temp "$id")
echo "$(device_name "$id"): temperature is $t, threshold is ${threshold}"
echo "$t ${threshold}" | awk '($1>$2) { exit 1 }'
