#!/bin/sh
set -eu

if [ $# -ne 2 ]; then
  echo "usage: $0 <host> <interface>" >&2
  exit 1
fi

SNMP_HOST=$1
SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

snmp get                 \
  -v "${SNMP_VERSION}"   \
  -c "${SNMP_COMMUNITY}" \
  "${SNMP_HOST}"         \
  "ifSpeed.$2"           \
  | awk '{ print $NF }'
