#!/bin/sh
#
# Ensures that there are at least <MINIMUM> processes named <PROC>.
#
# Usage: snmp_hrSWRun <PROC> <MINIMUM>
#
# You can get a list of available volumes with the command:
#
#   snmp walk -c <SNMP_COMMUNITY> -v <SNMP_VERSION> <SNMP_HOST> hrSWRunName
#

set -e
[ -n "${SNMP_HOST}" ] \
  || ( echo "SNMP_HOST is undefined" >&2 && exit 1 )

[ $# -ne 2 ] \
  && ( echo "command did not receive two arguments" >&2 && exit 1 )

set -eu

SNMP_VERSION=${SNMP_VERSION:-2c}
SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}

if [ "$(uname -s)" = "OpenBSD" ]; then
  SNMP_WALK="snmp walk"
else
  SNMP_WALK="snmpwalk"
fi

processCount() {
  ${SNMP_WALK} -v "${SNMP_VERSION}" -c "${SNMP_COMMUNITY}" "${SNMP_HOST}" hrSWRunName \
    | grep -c "STRING: $1$"
}

n=$(processCount "$1")
echo "$n"

[ "$n" -ge "$2" ]
