#!/usr/bin/env bash
#
# In the example:
#
#   md_degraded /dev/md0 5
#
# the script will return 1 unless there are:
#   - 5 active devices
#   - 5 working devices
#   - 0 spare devices
#   - 0 failed devices

md_dev="$1"
active_device_count="$2"
working_device_count="${3:-${active_device_count}}"
spare_device_count="${4:-0}"
failed_device_count="${4:-0}"

mdadm --detail "${md_dev}"                              \
  | awk -F' : '                                         \
        -v active_device_count=${active_device_count}   \
        -v working_device_count=${working_device_count} \
        -v spare_device_count=${spare_device_count}     \
        -v failed_device_count=${failed_device_count}   \
    '
      ($1~/Active Devices/) { if (int($2) != active_device_count ) { exit 1 }
      ($1~/Working Devices/) { if (int($2) != working_device_count ) { exit 1 }
      ($1~/Spare Devices/) { if (int($2) != spare_device_count ) { exit 1 }
      ($1~/Failed Devices/) { if (int($2) != failed_device_count ) { exit 1 }
    '
