#!/usr/bin/env bash

date >> /tmp/out.log
echo "${SUBJECT}" >> /tmp/out.log
echo "PRIORITY: ${PRIORITY}" >> /tmp/out.log
echo "SUBJECT: ${SUBJECT}" >> /tmp/out.log
echo "STATE: ${STATE}" >> /tmp/out.log
echo "LAST_STATE: ${LAST_STATE}" >> /tmp/out.log
cat >> /tmp/out.log
echo -e "\n\n" >> /tmp/out.log
