#!/bin/ksh
#
# $OpenBSD: flamingzombies, 0.0.1 2020/05/13 18:49:00 rpe Exp $

daemon="/usr/local/bin/fz"
rc_bg="YES"

. /etc/rc.d/rc.subr

rc_start() {
        rc_exec "${daemon} ${daemon_flags}"
}

rc_configtest() {
        rc_exec "${daemon} ${daemon_flags} -n"
}

rc_cmd $1
