.Dd 2024-05-02
.Dt fz 1
.Os
.Sh NAME
.Nm fz
.Nd A monitoring scheduler to detect failure and raise alerts.
.Sh SYNOPSIS
.Nm
.Op Fl n
.Op Fl c Ar file
.Op Fl l Ar error/warn/info/debug
.Sh DESCRIPTION
The
.Nm
daemon is a scheduler to perform monitoring tasks, detect state changes and raise alerts when appropriate.
.Pp
Although some scripts are provided, users are expected to write their own scripts which
.Nm
uses to perform the checks and decide whether a notification is raised. This makes it infinitely flexible, but does require a small amount of programming experience.
.Bl -tag -width Ds
.It Fl c, Li --config
The configuration file. See
.Xr fz-config
for details on how it can be configured.
.It Fl n, Li --configtest
Test the validity of the supplied configuration.
.Xr fz-config
for details on how it can be configured.
.It Fl C, Li --directory
The working directory from which scripts are executed. You may use relative paths from this directory when specifying task, notifier or gate commands.
.It Fl l, Li --loglevel
The level of logs that will be emitted. Valid options are error, warn, info or debug.
.It Fl V, Li --version
Print the version information.
.El
.Sh ENVIRONMENT
Most settings can also be supplied with environment variables, but if a command arguments is provided it will take precedence. The supported environment variables are listed below and closely match the arguments documented above.
.Bl -tag -width Ds
.It Ic FZ_CONFIG_FILE
.It Ic FZ_DIRECTORY
.It Ic FZ_LISTEN
.It Ic FZ_LOG_LEVEL
.El
.Sh SEE ALSO
.Xr fzctl 1 ,
.Xr flamingzombies.toml 5
.Sh "BUGS"
.Nm flamingzombies
is very immature. I'm sure it contains bugs and missing features.
