.Dd 2024-05-01
.Dt fzctl 1
.Os
.Sh NAME
.Nm fzctl
.Nd Run commands against an fz daemon.
.Sh SYNOPSIS
.Nm
.Op options
.Ar list
.Op ok|fail|unknown
.Nm
.Op options
.Ar show
.Ar task
.Op task...
.Sh DESCRIPTION
Control an
.Nm fz
daemon, or query its internal state.
.Pp
.Bl -tag -width Ds
.It Fl c, Li --config
The
.Nm fz
configuration file. It will connect to the
.Xr listen_address
unless the --host flag was supplied.
.It Fl H, Li --host
The IP address and port of the
.Nm fz
daemon to connect to. The default value is 127.0.0.1:5891.
.It Fl V, Li --version
Print the version information.
.El
.Sh ENVIRONMENT
Some settings can also be supplied with environment variables, but if a command arguments is provided it will take precedence.
.Bl -tag -width Ds
.It Ic FZ_LISTEN
The network address that the
.Xr fz 1
daemon is listening on.
.El
.Sh SEE ALSO
.Xr fz 1 ,
.Xr flamingzombies.toml 5
